name: Test

on:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install packages
        run: npm ci

      # need to fix this
      # - name: Lint
      #   run: npm run lint

      # - name: Lint markdown
      #   run: npm run lint:markdown

      # need to roll back type checks gradually
      # - name: Type checks
      #   run: npm run type-check

      # - name: Test Insomnium
      #   run: npm test -w packages/insomnial

      # - name: Test Insomnium Testing
      #   run: npm test -w packages/insomnial-testing
      # - name: Build app for smoke tests
      #   run: NODE_OPTIONS='--max_old_space_size=6144' npm run app-build

      # - name: Smoke test electron app
      #   # Partial Smoke test run, for regular CI triggers
      #   if: ${{ !startsWith(github.head_ref, 'release/') }}
      #   run: npm run test:build -w packages/insomnial-smoke-test -- --project=Smoke

      # - name: Prerelease test electron app
      #   # Full Smoke test run, for Release PRs
      #   if: ${{ startsWith(github.head_ref, 'release/') }}
      #   run: npm run test:build -w packages/insomnial-smoke-test -- --project=Default

      # #

      # - name: Upload smoke test traces
      #   uses: actions/upload-artifact@v3
      #   with:
      #     if-no-files-found: ignore
      #     name: ubuntu-smoke-test-traces-${{ github.run_number }}
      #     path: packages/insomnial-smoke-test/traces
